# This Logstash configuration file defines the input and output settings for processing logs from the Sentinel application. It listens for incoming log data in GELF format on UDP port 12201, which is commonly used for structured logging. The logs are expected to be in JSON format, allowing for easy parsing and analysis. The processed logs are then forwarded to Elasticsearch, where they are stored in an index named "sentinel-logs" with a date-based naming convention for efficient querying and management. This setup enables us to collect, store, and analyze logs from the Sentinel application effectively, providing insights into its performance and behavior.

input {
  udp {
    port => 12201
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sentinel-logs-%{+YYYY.MM.dd}"
  }
}