apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: localhost/docker_celery_worker:latest
        imagePullPolicy: Never
        command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
