apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel
resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - watchdog.yaml
  - status-api.yaml
  - ingestion.yaml
  - celery-worker.yaml
  - brain.yaml
  - prometheus-config.yaml
  - prometheus.yaml
