apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchdog
  template:
    metadata:
      labels:
        app: watchdog
    spec:
      containers:
      - name: watchdog
        image: localhost/docker_watchdog:latest
        imagePullPolicy: Never
        command: ["python", "watchdog.py"]
        env:
        - name: SENTINEL_ZMQ
          value: tcp://0.0.0.0:5555
        - name: SENTINEL_NODE_NAME
          value: Legion-5
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: watchdog
  namespace: sentinel
spec:
  selector:
    app: watchdog
  ports:
  - port: 5555
    targetPort: 5555
